tutorial/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (login,logout,
                                       password_reset,password_reset_done,password_reset_confirm,
                                       password_reset_complete,
                                    )


urlpatterns =[
    url(r'^$', views.home),
    url(r'^login/$', login,{'template_name':'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout,{'template_name':'accounts/logout.html'}, name='logout'),
    url(r'^register/$',views.register, name='register'),
    url(r'^profile/$',views.view_profile, name='view_profile'),
    url(r'^profile/edit/$',views.edit_profile, name='edit_profile'),
    url(r'^change-password/$',views.change_password, name='change_password'),

    url(r'^password-reset/$',password_reset,{'template_name':'accounts/reset_password.html',
        'post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/reset_password_email.html'},
        name='password_reset'),

    url(r'^password-reset/done/$',password_reset_done,{'template_name':'accounts/reset_password_done.html'}
        ,name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,{'template_name':'accounts/reset_password_confirm.html','post_reset_redirect':'accounts:password_reset_complete'},name='password_reset_confirm'),

    url(r'^password-reset/complete/$',password_reset_complete,{'template_name':'accounts/reset_password_complete.html'},
        name='password_reset_complete')
]

tutorial/tutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from tutorial import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect,name ='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100,default='')
    city = models.CharField(max_length=100,default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

tutorial/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields ={'username',
                 'first_name',
                 'last_name',
                 'email',
                 'password1',
                 'password2',
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

class ProfileEditForm(UserChangeForm):

    class Meta:
        model = User
        fields ={
            'email',
            'first_name',
            'password',
            'last_name',
        }

tutorial/accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import RegistrationForm,ProfileEditForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
#@login_required
def home(request):
    name="Satyendra Tiwari"
    numbers=[1,2,3,4,5]
    args={'myname':name,'numbers':numbers}
    return render(request,'accounts/home.html',args)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account')
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

#@login_required
def view_profile(request):
    args = {'user':request.user}
    return render(request, 'accounts/profile.html', args)

#@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/account/profile')
    else:
        form = ProfileEditForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

#@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect('/account/change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

tutorial/tutorial/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('account/login')

tutorial/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Change Password</title>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Change Password</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <br/>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <br/>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/home.html
{% extends 'base.html' %}

<h1>HOME</h1>
{% block head %}
<title>Home</title>
{% endblock %}

{% block body%}
<div class="container">
  <h2>Home Page</h2>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Welcome</h1>
  <p1>You can login here</p1>
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Logged out</h1>
  <p1>You have logged out!</p1>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Profile</h1>
  <p>User name: {{ user }}</p>
  <p>First name: {{ user.first_name }}</p>
  <p>Last name: {{ user.last_name }}</p>
  <p>Email: {{ user.email }}</p>
  <p>Description: {{ user.userprofile.description }}</p>
  <p>Phone: {{ user.userprofile.phone }}</p>
  <p>City: {{ user.userprofile.city }}</p>
  <p>website: {{ user.userprofile.website }}</p>
  {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="500">
  {% endif %}
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Register</h1>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Reset Password</h1>
  <p1>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Password reset complete</h1>
  <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Enter new password</h1>
  <p1></p1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password</button>
  </form>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Reset password send</h1>
  <p1>
    We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
    If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p1>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}

tutorial/accounts/templates/base.html
<html>
<head>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
  <link rel="stylesheet" type="text/css" href="style.css">
  {% block head %}
  <title>Base</title>
  {% endblock %}
</head>
<body>
<br/>
<div class="container">
      <!-- Static navbar -->
      <nav class="navbar navbar-dark bg-primary">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a style="color:white" class="navbar-brand" href="/">
              <b> Bista Solutions Inc.</b>
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            {% if request.user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li><a style="color:black" href="/account">Home</a></li>
              <li><a style="color:black" href="{% url 'accounts:view_profile' %}">Profile</a></li>
              <li><a style="color:black" href="/account/profile/edit">Profile Edit</a></li>
              <li><a style="color:black" style="color:black" href="/account/change-password">change Password</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a style="color:black" href="/account/logout">Log out</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
              <li><a style="color:black" href="/account/password-reset">Reset Password</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a style="color:black" href="/account/login">Login</a></li>
              <li><a style="color:black" href="/account/register">Register</a></li>
            </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
</div>
{% block body %}
<h1>Base.......</h1>
{% endblock %}
</body>
</html>